### ISSUE TITLE
Vampiric Touch

### ISSUE THREAD

**Issue by Darkpriestx** [kesava-wow/kuispelllist#1]
The same problem and the ability to Agony.I made a video that shows my problem.https://youtu.be/NnLBrRbbZ-4

**Comment by kesava-wow** [comment]
Thanks, I'll check this... Probably tomorrow.

**Comment by Darkpriestx** [comment]
ok,thanks for answer

**Comment by kesava-wow** [comment]
Could you give me a screenshot of your /knp > auras interface page?

**Comment by Darkpriestx** [comment]
![wowscrnshot_072216_195401](https://cloud.githubusercontent.com/assets/20583560/17064658/4ad615aa-5046-11e6-867d-3606b874e349.jpg)

**Comment by kesava-wow** [comment]
Yeah, this is caused by the "maximum effect length" setting. When you reapply vampiric touch or agony that soon, its length exceeds what you've got set there, so it gets hidden.

The idea with that setting is to never show auras which have an initial length longer than that value - i.e. they won't get shown again, even when they go below that value, unless they fall off or if you manage to reapply them with a shorter length.

So yeah, you might want to raise that setting. Apologies for the confusion.

**Comment by Darkpriestx** [comment]
Thank you, it was my fault

**Comment by Darkpriestx** [comment]
Now it works
